/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOrganizationIdRouteRouteImport } from './routes/app/$organizationId/route'
import { Route as AppCreateOrganizationIndexRouteImport } from './routes/app/create-organization/index'
import { Route as AppOrganizationIdIndexRouteImport } from './routes/app/$organizationId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationIdProductsIndexRouteImport } from './routes/app/$organizationId/products/index'
import { Route as AppOrganizationIdClientsIndexRouteImport } from './routes/app/$organizationId/clients/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationIdRouteRoute = AppOrganizationIdRouteRouteImport.update({
  id: '/$organizationId',
  path: '/$organizationId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateOrganizationIndexRoute =
  AppCreateOrganizationIndexRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationIdIndexRoute = AppOrganizationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationIdProductsIndexRoute =
  AppOrganizationIdProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AppOrganizationIdRouteRoute,
  } as any)
const AppOrganizationIdClientsIndexRoute =
  AppOrganizationIdClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AppOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$organizationId': typeof AppOrganizationIdRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/app/create-organization/': typeof AppCreateOrganizationIndexRoute
  '/app/$organizationId/clients/': typeof AppOrganizationIdClientsIndexRoute
  '/app/$organizationId/products/': typeof AppOrganizationIdProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId': typeof AppOrganizationIdIndexRoute
  '/app/create-organization': typeof AppCreateOrganizationIndexRoute
  '/app/$organizationId/clients': typeof AppOrganizationIdClientsIndexRoute
  '/app/$organizationId/products': typeof AppOrganizationIdProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$organizationId': typeof AppOrganizationIdRouteRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationId/': typeof AppOrganizationIdIndexRoute
  '/app/create-organization/': typeof AppCreateOrganizationIndexRoute
  '/app/$organizationId/clients/': typeof AppOrganizationIdClientsIndexRoute
  '/app/$organizationId/products/': typeof AppOrganizationIdProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$organizationId'
    | '/app/'
    | '/api/auth/$'
    | '/app/$organizationId/'
    | '/app/create-organization/'
    | '/app/$organizationId/clients/'
    | '/app/$organizationId/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/app/$organizationId'
    | '/app/create-organization'
    | '/app/$organizationId/clients'
    | '/app/$organizationId/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$organizationId'
    | '/app/'
    | '/api/auth/$'
    | '/app/$organizationId/'
    | '/app/create-organization/'
    | '/app/$organizationId/clients/'
    | '/app/$organizationId/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$organizationId': {
      id: '/app/$organizationId'
      path: '/$organizationId'
      fullPath: '/app/$organizationId'
      preLoaderRoute: typeof AppOrganizationIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/create-organization/': {
      id: '/app/create-organization/'
      path: '/create-organization'
      fullPath: '/app/create-organization/'
      preLoaderRoute: typeof AppCreateOrganizationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$organizationId/': {
      id: '/app/$organizationId/'
      path: '/'
      fullPath: '/app/$organizationId/'
      preLoaderRoute: typeof AppOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationId/products/': {
      id: '/app/$organizationId/products/'
      path: '/products'
      fullPath: '/app/$organizationId/products/'
      preLoaderRoute: typeof AppOrganizationIdProductsIndexRouteImport
      parentRoute: typeof AppOrganizationIdRouteRoute
    }
    '/app/$organizationId/clients/': {
      id: '/app/$organizationId/clients/'
      path: '/clients'
      fullPath: '/app/$organizationId/clients/'
      preLoaderRoute: typeof AppOrganizationIdClientsIndexRouteImport
      parentRoute: typeof AppOrganizationIdRouteRoute
    }
  }
}

interface AppOrganizationIdRouteRouteChildren {
  AppOrganizationIdIndexRoute: typeof AppOrganizationIdIndexRoute
  AppOrganizationIdClientsIndexRoute: typeof AppOrganizationIdClientsIndexRoute
  AppOrganizationIdProductsIndexRoute: typeof AppOrganizationIdProductsIndexRoute
}

const AppOrganizationIdRouteRouteChildren: AppOrganizationIdRouteRouteChildren =
  {
    AppOrganizationIdIndexRoute: AppOrganizationIdIndexRoute,
    AppOrganizationIdClientsIndexRoute: AppOrganizationIdClientsIndexRoute,
    AppOrganizationIdProductsIndexRoute: AppOrganizationIdProductsIndexRoute,
  }

const AppOrganizationIdRouteRouteWithChildren =
  AppOrganizationIdRouteRoute._addFileChildren(
    AppOrganizationIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppOrganizationIdRouteRoute: typeof AppOrganizationIdRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCreateOrganizationIndexRoute: typeof AppCreateOrganizationIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOrganizationIdRouteRoute: AppOrganizationIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCreateOrganizationIndexRoute: AppCreateOrganizationIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
